### ISSUE TITLE
Unreasonable replicated explanations 

### ISSUE THREAD

**Issue by haozheji** [salesforce/cos-e#2]
Hi! I found there exists many replicated "open-minded" explanations in both train/dev sets. I count the number and here are the statistics:
In dev set:
```
[('Rivers flow trough valleys.', 114),
 ('This word is Most relavant', 50),
 ('This word was most relevant.', 30),
 ('This option is better to this task.', 17),
 ('this word is more relevant', 15),
 ('THIS IS BETTER ANSWER', 9),
 ('A person is a human', 6),
 ('Rivers flow trough valleys', 5)]
```
and train set:
```
[('rivers flow trough valleys.', 386),
 ('this word is most relavant', 253),
 ('this word was most relevant.', 135),
 ('health complications', 134),
 ('this word is more relevant', 39),
 ('gritting your teeth', 25),
 ('rivers flow trough valleys', 24),
```
I couldn't understand why is the "rivers flow trough valleys" repeated so many times so I check some examples that have it as an explanation.
1. Where would you get jeans and other wearable items to take home with you?
2. In what substance do clouds float?
3. Where is food likely to stay dry?
4. It's dangerous to let pet birds free so it's better to keep them what?
...

Seems to me this explanation is likely to uncorrelated with most examples and also many uninformative explanations such as 'the word is most relevant' doesn't even provide any rationale to the question. I'm wondering have you check the quality of those explanations written by annotators?

**Comment by sarahwie** [comment]
I noticed these too, but only in the v1.11 version. Is there any reason why they've appeared in the newer version of the dataset? Thanks!

**Comment by ghost** [comment]
Thanks for bringing this up. The v1.11 of CQA was more adversarial in that multiple options were very likely to be the correct answer and required very subtle reasoning. For example "If somebody is working at a reception desk, they are located at the front entrance of the what?" with options "office park, motel, lobby, hostel, building" with the ground truth answer "building". This is difficult for humans to justify very easily and so they end up using phrases like "this word is more relevant" or "this option is better". 

Ideally, we would expect Mturkers to justify the ground truth answer by explaining discriminative features about that option but it is not very straightforward for many questions in v1.11. 

We did our best to get high-quality explanations even with the bigger v1.11 dataset but it is possible some examples might have fallen through the cracks.

Other examples I saw by eyeballing the CQA v1.11 dev set:
"What does everyone have in relation to other people?, feelings, food, unique personality, different standards, values" with "feelings" as the ground truth. 
"Where could a person avoid the rain?,street corner,tunnel,synagogue,bus stop,fairy tale"

**Comment by sarahwie** [comment]
Thanks for the clarification, Nazneen! Could you provide insight on the noisier examples mentioned, such as those brought up in the [WT5? paper](https://colinraffel.com/publications/arxiv2020wt5.pdf) or the "rivers flow trough valleys" and "health complications" explanations mentioned above? Is it possible these are due to Turkers cheating the evaluation, or a misalignment? I found the low result reported for humans in the WT5? paper section 4.4 surprising, and the authors mention these annotations being the source.

Examples from WT5? paper:
- “Little sarah didn’t think that anyone should be kissing boys.  She thought that boys had what?”. answer “cooties”. annotated with explanation “american horror comedy film directed”.
- question “What do you fill with ink to print?”  with answer “printer” annotated with the explanation “health complications” (134 times)
